spring:
  profiles:
    # 使用的配置文件，如果是application-run.yml则为run，如果是application-dev.yml则为dev
    active: run
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 20MB
      #单次请求文件的总大小
      max-request-size: 20MB

  messages:
    encoding: utf-8

#默认评论头像
comment.avatar: /images/Common/comment-avator1.png