spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxxxxx
    password: xxxxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.xinglongfei.blog: debug
  file:
    path: log/blog-dev.log

server:
  port: 8080

#阿里云存储(OSS)配置
#阿里云主账号AccessKey拥有所有API的访问权限，风险很高。建议创建并使用RAM账号进行API访问或日常运维，请登录 https://ram.console.aliyun.com 创建RAM账号。
oss:
  protocol: https
  endpoint: xxxxxx #填写bucket所在的地域节点
  keyid:    xxxxxxx # 填写AccessKey
  keysecret: xxxxxxx  # 填写Accesssecret
  bucketname: xxxxxx # 仓库名称
  domainname: xxxxxxx    #bucket绑定的域名


blog:
  index: http://127.0.0.1:8080
    authoremail: xxxx #博主邮箱，用来提醒博客有人评论了

#发送邮箱的配置信息
email:
  host: xxxxx #邮箱服务商,126邮箱为smtp.126.com,163邮箱为163.smtp.com，QQ为smtp.qq.com
  charset: xxxxx  #邮件字符集
  sender: xxxxx  #发件人邮箱
  sendername: xxxxx   #发件昵称
  authorcode: xxxxx   #邮箱STMP/POP3授权码
  subject: xxxxx   #邮件主题


